export const TOOLTIPS = [
  {
    id: 'care_mode_first_visit',
    target: 'bottom-tab-care',
    title: 'Care mode',
    body: 'Only plants that need attention today. Sorted by urgency. No scrolling through your whole collection.',
    position: 'top',
  },
  {
    id: 'care_today_first_visit',
    target: 'care-today-tab',
    title: 'Care mode',
    body: 'Only the plants that need attention today, sorted by urgency. No scrolling through your whole collection.',
    position: 'bottom',
    delayMs: 500,
  },
  {
    id: 'care_growth_first_visit',
    target: 'care-growth-tab',
    title: 'Growth',
    body: 'Track how your plants are doing over time. Health scores, care history, photo timelines, and propagation — all in one place.',
    position: 'bottom',
    delayMs: 500,
  },
  {
    id: 'care_goals_first_visit',
    target: 'care-goals-tab',
    title: 'Goals and badges',
    body: 'Set personal plant goals and earn badges as you reach milestones.',
    position: 'bottom',
    delayMs: 500,
  },
  {
    id: 'bulk_water_first_visit',
    target: 'water-all-button',
    title: 'Weekly water round',
    body: 'Log water for your whole collection in one tap. Monthly plants are auto-excluded when not yet due.',
    position: 'top',
  },
  {
    id: 'status_dot_first_visit',
    target: 'collection-grid-plant-tile',
    title: 'Status dots',
    body: 'Green = all good. Amber = water soon. Pink = overdue. Teal = propagating. Scan your whole collection in seconds.',
    position: 'bottom',
  },
  {
    id: 'streak_first_log',
    target: 'profile-stats-card',
    title: 'Your streak starts now',
    body: 'Log care every day to grow your streak. At day 7 the social feed unlocks. At day 30 swap matching unlocks.',
    position: 'bottom',
  },
  {
    id: 'bouquet_first_visit',
    target: 'bottom-tab-bouquets',
    title: 'Track bouquets',
    body: 'Photograph any arrangement. Grove identifies every flower and builds a personalized care plan to extend its life.',
    position: 'top',
  },
  {
    id: 'feed_first_visit',
    target: 'bottom-tab-feed',
    title: 'Community feed',
    body: 'See what your grove members are growing. Share updates, react with leaf/light/cutting, and learn from each other.',
    position: 'top',
  },
];
